In [1]:
import os
import pickle
import pandas as pd
from gensim.models import KeyedVectors
import numpy as np
from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import StratifiedKFold, GridSearchCV, train_test_split, HalvingGridSearchCV
from sklearn.neural_network import MLPClassifier

from data import preprocess_data, vectorize_data, load_dataset
from evaluation import analysis, evaluate_models_with_data
from w2v_adapter import Word2VecAdapter

import advanced_processor_chain_factory
import simple_processor_chain_factory

In [2]:
dataset = load_dataset()
DEBUG = False    

# Inspection of Pre-Processing Approaches

In [3]:
models = {'logistic regression' : LogisticRegression(class_weight = 'balanced', n_jobs=-1),
          'svm' : svm.LinearSVC(),
          'knn' : KNeighborsClassifier(n_neighbors=8, n_jobs=-1)
         }

## Without Pre-Process

In [4]:
evaluate_models_with_data(models, *vectorize_data(*preprocess_data(dataset, debug=DEBUG), CountVectorizer(max_features=2000)))

------Evaluating logistic regression------
Report: Classification
               precision    recall  f1-score   support

    positive       0.88      0.87      0.87      5586
    negative       0.87      0.89      0.88      5664

    accuracy                           0.88     11250
   macro avg       0.88      0.88      0.88     11250
weighted avg       0.88      0.88      0.88     11250

Matrix: Confusion
 [[4842  744]
 [ 640 5024]]
Accuracy:
 0.8769777777777777
------Evaluating svm------


/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


Report: Classification
               precision    recall  f1-score   support

    positive       0.86      0.87      0.87      5586
    negative       0.87      0.86      0.87      5664

    accuracy                           0.87     11250
   macro avg       0.87      0.87      0.87     11250
weighted avg       0.87      0.87      0.87     11250

Matrix: Confusion
 [[4884  702]
 [ 774 4890]]
Accuracy:
 0.8688
------Evaluating knn------
Report: Classification
               precision    recall  f1-score   support

    positive       0.64      0.64      0.64      5586
    negative       0.64      0.64      0.64      5664

    accuracy                           0.64     11250
   macro avg       0.64      0.64      0.64     11250
weighted avg       0.64      0.64      0.64     11250

Matrix: Confusion
 [[3561 2025]
 [2017 3647]]
Accuracy:
 0.6407111111111111


## Simple Pre-Process

In [5]:
evaluate_models_with_data(models,
                          *vectorize_data(
                              *preprocess_data(dataset, processor_chain=simple_processor_chain_factory.create(), debug=DEBUG),
                              CountVectorizer(max_features=2000)))

Pandas Apply:   0%|          | 0/45000 [00:00<?, ?it/s]

------Evaluating logistic regression------
Report: Classification
               precision    recall  f1-score   support

    positive       0.87      0.87      0.87      5673
    negative       0.86      0.87      0.87      5577

    accuracy                           0.87     11250
   macro avg       0.87      0.87      0.87     11250
weighted avg       0.87      0.87      0.87     11250

Matrix: Confusion
 [[4914  759]
 [ 717 4860]]
Accuracy:
 0.8688
------Evaluating svm------


/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


Report: Classification
               precision    recall  f1-score   support

    positive       0.89      0.84      0.86      5673
    negative       0.85      0.89      0.87      5577

    accuracy                           0.87     11250
   macro avg       0.87      0.87      0.87     11250
weighted avg       0.87      0.87      0.87     11250

Matrix: Confusion
 [[4765  908]
 [ 602 4975]]
Accuracy:
 0.8657777777777778
------Evaluating knn------
Report: Classification
               precision    recall  f1-score   support

    positive       0.65      0.62      0.63      5673
    negative       0.63      0.65      0.64      5577

    accuracy                           0.64     11250
   macro avg       0.64      0.64      0.64     11250
weighted avg       0.64      0.64      0.64     11250

Matrix: Confusion
 [[3525 2148]
 [1939 3638]]
Accuracy:
 0.6367111111111111


## Pre-Process with Stemmimg

In [6]:
evaluate_models_with_data(models,
                          *vectorize_data(
                              *preprocess_data(dataset, processor_chain=advanced_processor_chain_factory.create('stem'),
                                               debug=DEBUG),
                              CountVectorizer(max_features=2000)))

Pandas Apply:   0%|          | 0/45000 [00:00<?, ?it/s]

------Evaluating logistic regression------
Report: Classification
               precision    recall  f1-score   support

    positive       0.87      0.87      0.87      5601
    negative       0.87      0.88      0.87      5649

    accuracy                           0.87     11250
   macro avg       0.87      0.87      0.87     11250
weighted avg       0.87      0.87      0.87     11250

Matrix: Confusion
 [[4854  747]
 [ 702 4947]]
Accuracy:
 0.8712
------Evaluating svm------


/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


Report: Classification
               precision    recall  f1-score   support

    positive       0.88      0.86      0.87      5601
    negative       0.86      0.88      0.87      5649

    accuracy                           0.87     11250
   macro avg       0.87      0.87      0.87     11250
weighted avg       0.87      0.87      0.87     11250

Matrix: Confusion
 [[4818  783]
 [ 674 4975]]
Accuracy:
 0.8704888888888889
------Evaluating knn------
Report: Classification
               precision    recall  f1-score   support

    positive       0.63      0.81      0.71      5601
    negative       0.73      0.52      0.61      5649

    accuracy                           0.66     11250
   macro avg       0.68      0.67      0.66     11250
weighted avg       0.68      0.66      0.66     11250

Matrix: Confusion
 [[4523 1078]
 [2697 2952]]
Accuracy:
 0.6644444444444444


## Pre-Process with Lemmitization

In [7]:
X, Y = preprocess_data(dataset, processor_chain=advanced_processor_chain_factory.create('lem'), debug=DEBUG)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y)
del dataset

Pandas Apply:   0%|          | 0/45000 [00:00<?, ?it/s]

In [8]:
vectorizer = CountVectorizer(max_features=2000)
X_train_bow = vectorizer.fit_transform(X_train)
X_test_bow = vectorizer.transform(X_test)

In [9]:
evaluate_models_with_data(models, X_train_bow, X_test_bow, Y_train, Y_test)

------Evaluating logistic regression------
Report: Classification
               precision    recall  f1-score   support

    positive       0.88      0.86      0.87      5688
    negative       0.86      0.88      0.87      5562

    accuracy                           0.87     11250
   macro avg       0.87      0.87      0.87     11250
weighted avg       0.87      0.87      0.87     11250

Matrix: Confusion
 [[4865  823]
 [ 660 4902]]
Accuracy:
 0.8681777777777778
------Evaluating svm------


/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


Report: Classification
               precision    recall  f1-score   support

    positive       0.88      0.85      0.86      5688
    negative       0.85      0.88      0.87      5562

    accuracy                           0.87     11250
   macro avg       0.87      0.87      0.87     11250
weighted avg       0.87      0.87      0.87     11250

Matrix: Confusion
 [[4847  841]
 [ 676 4886]]
Accuracy:
 0.8651555555555556
------Evaluating knn------
Report: Classification
               precision    recall  f1-score   support

    positive       0.63      0.81      0.71      5688
    negative       0.73      0.51      0.60      5562

    accuracy                           0.66     11250
   macro avg       0.68      0.66      0.66     11250
weighted avg       0.68      0.66      0.66     11250

Matrix: Confusion
 [[4632 1056]
 [2726 2836]]
Accuracy:
 0.6638222222222222


In [10]:
del models

# Compare W2V and BoW with Their Best Tuned Hyper-parameters

In [23]:
kfold = StratifiedKFold(n_splits=5)
general_grid_params = {'verbose' : 1, 'cv' : kfold, 'n_jobs' : -1, 'scoring' : 'f1'}

logistic_grid = {
    'penalty':['l2'],
    'C':[1, 300, 500, 700, 900, 2000],
    'class_weight':['balanced'],
    'solver':['saga'],
    'n_jobs':[-1],
    'max_iter':[1000],
}

svc_grid = {
    'kernel' : ['linear', 'rbf'],
    'C':[0.1, 1, 500, 1000],
}

knn_grid = {
    'n_neighbors' : [1, 100, 300, 500, 700, 900, 2000],
    'n_jobs' : [-1]
}

## BoW

### Logistic Regression

In [12]:
bow_log = LogisticRegression()
bow_log = GridSearchCV(estimator=bow_log, param_grid=logistic_grid, **general_grid_params)
bow_log.fit(X_train_bow, Y_train)
print(f'Best Score: {bow_log.best_score_}')
print(f'Best Params: {bow_log.best_params_}')
pd.DataFrame(bow_log.cv_results_)

Fitting 5 folds for each of 6 candidates, totalling 30 fits


/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "


Best Score: 0.8657995144389071
Best Params: {'C': 1, 'class_weight': 'balanced', 'max_iter': 1000, 'n_jobs': -1, 'penalty': 'l2', 'solver': 'saga'}


mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0      86.863498      0.486335         0.019102        0.004084       1   
1      85.363447      1.895883         0.017772        0.006606     300   
2      85.480270      1.190058         0.014565        0.004605     500   
3      86.605620      1.691871         0.012728        0.001570     700   
4      85.209331      3.334262         0.012569        0.002099     900   
5      79.500330      0.926723         0.011064        0.001510    2000   

  param_class_weight param_max_iter param_n_jobs param_penalty param_solver  \
0           balanced           1000           -1            l2         saga   
1           balanced           1000           -1            l2         saga   
2           balanced           1000           -1            l2         saga   
3           balanced           1000           -1            l2         saga   
4           balanced           1000           -1            l2         saga   
5           balanced           1000           -1            l2         saga   

                                              params  split0_test_score  \
0  {'C': 1, 'class_weight': 'balanced', 'max_iter...           0.868440   
1  {'C': 300, 'class_weight': 'balanced', 'max_it...           0.866123   
2  {'C': 500, 'class_weight': 'balanced', 'max_it...           0.866249   
3  {'C': 700, 'class_weight': 'balanced', 'max_it...           0.866123   
4  {'C': 900, 'class_weight': 'balanced', 'max_it...           0.866123   
5  {'C': 2000, 'class_weight': 'balanced', 'max_i...           0.866123   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.860537           0.871598           0.859662           0.868761   
1           0.861042           0.870748           0.858529           0.867264   
2           0.861042           0.870748           0.858697           0.867264   
3           0.861042           0.870748           0.858697           0.867264   
4           0.861042           0.870748           0.858529           0.867264   
5           0.861042           0.870748           0.858529           0.867264   

   mean_test_score  std_test_score  rank_test_score  
0         0.865800        0.004790                1  
1         0.864741        0.004396                4  
2         0.864800        0.004357                2  
3         0.864775        0.004349                3  
4         0.864741        0.004396                4  
5         0.864741        0.004396                4

In [13]:
analysis(Y_test, bow_log.predict(X_test_bow))

Report: Classification
               precision    recall  f1-score   support

    positive       0.88      0.86      0.87      5688
    negative       0.86      0.88      0.87      5562

    accuracy                           0.87     11250
   macro avg       0.87      0.87      0.87     11250
weighted avg       0.87      0.87      0.87     11250

Matrix: Confusion
 [[4866  822]
 [ 664 4898]]
Accuracy:
 0.8679111111111111


0.8682857649352952

### SVM

In [14]:
bow_svm = svm.SVC()
bow_svm = HalvingGridSearchCV(estimator=bow_svm, param_grid=svc_grid, cv = 4, n_jobs= -1, scoring='f1', factor=2)
bow_svm.fit(X_train_bow, Y_train)
print(f'Best Score: {bow_svm.best_score_}')
print(f'Best Params: {bow_svm.best_params_}')
pd.DataFrame(bow_svm.cv_results_)

Best Score: 0.8677297881739967
Best Params: {'C': 1, 'kernel': 'rbf'}


iter  n_resources  mean_fit_time  std_fit_time  mean_score_time  \
0      0         4218       5.788482      0.624874         1.049996   
1      0         4218      10.294384      1.200383         3.128312   
2      0         4218       5.961231      0.748652         0.980025   
3      0         4218       8.308554      1.224831         2.027000   
4      0         4218       6.611430      0.553976         1.012758   
5      0         4218      11.814751      1.351137         2.206957   
6      0         4218       6.837007      0.813769         0.957066   
7      0         4218       8.436112      0.805540         1.636469   
8      1         8436      29.782039      4.290875         5.528334   
9      1         8436      49.428387      5.780353         9.974282   
10     1         8436      63.143489      8.322508        12.443996   
11     1         8436      44.116952      3.300405        10.025893   
12     2        16872     548.153594     16.831312        33.671474   
13     2        16872     218.516705     28.942298        51.999593   
14     3        33744    1089.787780    119.876066       128.671901   

    std_score_time param_C param_kernel                           params  \
0         0.088975     0.1       linear   {'C': 0.1, 'kernel': 'linear'}   
1         0.352425     0.1          rbf      {'C': 0.1, 'kernel': 'rbf'}   
2         0.011628       1       linear     {'C': 1, 'kernel': 'linear'}   
3         0.126436       1          rbf        {'C': 1, 'kernel': 'rbf'}   
4         0.088587     500       linear   {'C': 500, 'kernel': 'linear'}   
5         0.143414     500          rbf      {'C': 500, 'kernel': 'rbf'}   
6         0.069734    1000       linear  {'C': 1000, 'kernel': 'linear'}   
7         0.138795    1000          rbf     {'C': 1000, 'kernel': 'rbf'}   
8         0.435915     0.1       linear   {'C': 0.1, 'kernel': 'linear'}   
9         1.943730     500          rbf      {'C': 500, 'kernel': 'rbf'}   
10        0.449354    1000          rbf     {'C': 1000, 'kernel': 'rbf'}   
11        0.822324       1          rbf        {'C': 1, 'kernel': 'rbf'}   
12        0.957212    1000          rbf     {'C': 1000, 'kernel': 'rbf'}   
13        2.774354       1          rbf        {'C': 1, 'kernel': 'rbf'}   
14        9.652677       1          rbf        {'C': 1, 'kernel': 'rbf'}   

    split0_test_score  ...  split3_test_score  mean_test_score  \
0            0.815672  ...           0.825070         0.820762   
1            0.765957  ...           0.766387         0.762559   
2            0.794326  ...           0.801153         0.798872   
3            0.831633  ...           0.838710         0.836093   
4            0.791111  ...           0.801914         0.797348   
5            0.828179  ...           0.839890         0.829271   
6            0.791111  ...           0.801914         0.797348   
7            0.828179  ...           0.839890         0.829271   
8            0.836153  ...           0.825247         0.828270   
9            0.841856  ...           0.817204         0.830358   
10           0.841856  ...           0.817204         0.830358   
11           0.853818  ...           0.835698         0.843522   
12           0.851242  ...           0.842871         0.846499   
13           0.868326  ...           0.864129         0.861876   
14           0.870025  ...           0.868321         0.867730   

    std_test_score  rank_test_score  split0_train_score  split1_train_score  \
0         0.007773               11            0.983212            0.980141   
1         0.007976               15            0.782804            0.785379   
2         0.004893               12            1.000000            0.999694   
3         0.002797                5            0.948428            0.944411   
4         0.004679               13            1.000000            1.000000   
5         0.008183                8            1.000000            1.000000   
6         0.004679               13     

In [18]:
analysis(Y_test, bow_svm.predict(X_test_bow))

Report: Classification
               precision    recall  f1-score   support

    positive       0.89      0.84      0.87      5688
    negative       0.85      0.90      0.87      5562

    accuracy                           0.87     11250
   macro avg       0.87      0.87      0.87     11250
weighted avg       0.87      0.87      0.87     11250

Matrix: Confusion
 [[4777  911]
 [ 577 4985]]
Accuracy:
 0.8677333333333334


0.8701344039099319

### KNN

In [24]:
bow_knn = KNeighborsClassifier()
bow_knn = HalvingGridSearchCV(estimator=bow_knn, param_grid=knn_grid, cv = 4, scoring='f1', factor=2)
bow_knn.fit(X_train_bow, Y_train)
print(f'Best Score: {bow_knn.best_score_}')
print(f'Best Params: {bow_knn.best_params_}')
pd.DataFrame(bow_knn.cv_results_)

Best Score: 0.7344377977492681
Best Params: {'n_jobs': -1, 'n_neighbors': 300}


iter  n_resources  mean_fit_time  std_fit_time  mean_score_time  \
0      0         8437       0.009809      0.001351         0.753061   
1      0         8437       0.011755      0.001151         1.033305   
2      0         8437       0.010428      0.001356         1.004717   
3      0         8437       0.013292      0.005359         1.175060   
4      0         8437       0.011536      0.002371         1.238360   
5      0         8437       0.011441      0.002858         1.322407   
6      0         8437       0.011688      0.002260         1.856229   
7      1        16874       0.021313      0.003518         4.095783   
8      1        16874       0.022560      0.003252         4.803890   
9      1        16874       0.022476      0.001762         3.528790   
10     1        16874       0.021722      0.001080         3.369626   
11     2        33748       0.037431      0.004346        12.846309   
12     2        33748       0.038344      0.002039        12.834630   

    std_score_time param_n_jobs param_n_neighbors  \
0         0.032235           -1                 1   
1         0.120803           -1               100   
2         0.033191           -1               300   
3         0.053505           -1               500   
4         0.057155           -1               700   
5         0.049513           -1               900   
6         0.096936           -1              2000   
7         0.113402           -1               900   
8         0.337252           -1              2000   
9         0.058324           -1               300   
10        0.144657           -1               100   
11        0.957715           -1               100   
12        0.347045           -1               300   

                                 params  split0_test_score  ...  \
0      {'n_jobs': -1, 'n_neighbors': 1}           0.555783  ...   
1    {'n_jobs': -1, 'n_neighbors': 100}           0.715699  ...   
2    {'n_jobs': -1, 'n_neighbors': 300}           0.699401  ...   
3    {'n_jobs': -1, 'n_neighbors': 500}           0.698313  ...   
4    {'n_jobs': -1, 'n_neighbors': 700}           0.699098  ...   
5    {'n_jobs': -1, 'n_neighbors': 900}           0.697582  ...   
6   {'n_jobs': -1, 'n_neighbors': 2000}           0.701079  ...   
7    {'n_jobs': -1, 'n_neighbors': 900}           0.710148  ...   
8   {'n_jobs': -1, 'n_neighbors': 2000}           0.708627  ...   
9    {'n_jobs': -1, 'n_neighbors': 300}           0.735464  ...   
10   {'n_jobs': -1, 'n_neighbors': 100}           0.715392  ...   
11   {'n_jobs': -1, 'n_neighbors': 100}           0.728983  ...   
12   {'n_jobs': -1, 'n_neighbors': 300}           0.743604  ...   

    split3_test_score  mean_test_score  std_test_score  rank_test_score  \
0            0.598049         0.595487        0.029178               13   
1            0.715470         0.706199        0.011554                5   
2            0.705882         0.702248        0.003463                8   
3            0.693164         0.695764        0.004095               11   
4            0.690174         0.695583        0.004860               12   
5            0.693878         0.697408        0.004057               10   
6            0.687122         0.698583        0.008963                9   
7            0.694182         0.703707        0.005973                7   
8            0.695548         0.704829        0.005779                6   
9            0.715121         0.725307        0.007271                2   
10           0.714620         0.716047        0.006775                4   
11           0.712874         0.717980        0.008379                3   
12           0.741508         0.734438        0.008856                1   

    split0_train_score  split1_train_score  split2_train_score  \
0             1.000000            1.000000            1.000000   
1             0.729865            0.710826            0.724062   
2             0.705944            0.701210            0.723704   
3           

In [25]:
analysis(Y_test, bow_svm.predict(X_test_bow))

Report: Classification
               precision    recall  f1-score   support

    positive       0.89      0.84      0.87      5688
    negative       0.85      0.90      0.87      5562

    accuracy                           0.87     11250
   macro avg       0.87      0.87      0.87     11250
weighted avg       0.87      0.87      0.87     11250

Matrix: Confusion
 [[4777  911]
 [ 577 4985]]
Accuracy:
 0.8677333333333334


0.8701344039099319

## W2V

In [26]:
if os.path.isfile('w2v.kv'):
    vectorizer = Word2VecAdapter(pre_trained_model=KeyedVectors.load('w2v.kv'))
else:
    vectorizer = Word2VecAdapter()

X_train_w2v = vectorizer.fit_transform(X_train)
X_test_w2v = vectorizer.transform(X_test)

if not os.path.isfile('w2v.kv'):
     vectorizer.wv.save('w2v.kv')

Pandas Apply:   0%|          | 0/33750 [00:00<?, ?it/s]

Pandas Apply:   0%|          | 0/33750 [00:00<?, ?it/s]

Pandas Apply:   0%|          | 0/11250 [00:00<?, ?it/s]

### Logistic Regression

In [27]:
w2v_log = LogisticRegression()
w2v_log = GridSearchCV(estimator=w2v_log, param_grid=logistic_grid, **general_grid_params)
w2v_log.fit(X_train_w2v, Y_train)
print(f'Best Score: {w2v_log.best_score_}')
print(f'Best Params: {w2v_log.best_params_}')
pd.DataFrame(w2v_log.cv_results_)

Fitting 5 folds for each of 6 candidates, totalling 30 fits
Best Score: 0.8673145284043511
Best Params: {'C': 900, 'class_weight': 'balanced', 'max_iter': 1000, 'n_jobs': -1, 'penalty': 'l2', 'solver': 'saga'}


mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0      63.494407      3.185043         0.025942        0.009875       1   
1     166.584122     17.958926         0.020381        0.003884     300   
2     156.931494     14.240462         0.023535        0.001406     500   
3     158.189548     11.045858         0.018214        0.002789     700   
4     159.282837      8.879876         0.022290        0.005948     900   
5     158.081150      6.700318         0.015832        0.002311    2000   

  param_class_weight param_max_iter param_n_jobs param_penalty param_solver  \
0           balanced           1000           -1            l2         saga   
1           balanced           1000           -1            l2         saga   
2           balanced           1000           -1            l2         saga   
3           balanced           1000           -1            l2         saga   
4           balanced           1000           -1            l2         saga   
5           balanced           1000           -1            l2         saga   

                                              params  split0_test_score  \
0  {'C': 1, 'class_weight': 'balanced', 'max_iter...           0.867902   
1  {'C': 300, 'class_weight': 'balanced', 'max_it...           0.869095   
2  {'C': 500, 'class_weight': 'balanced', 'max_it...           0.869095   
3  {'C': 700, 'class_weight': 'balanced', 'max_it...           0.868968   
4  {'C': 900, 'class_weight': 'balanced', 'max_it...           0.869095   
5  {'C': 2000, 'class_weight': 'balanced', 'max_i...           0.869095   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.865685           0.866499           0.861005           0.865861   
1           0.865421           0.869719           0.862861           0.869310   
2           0.865421           0.869719           0.862861           0.869016   
3           0.865421           0.869886           0.862861           0.869310   
4           0.865421           0.869886           0.862861           0.869310   
5           0.865421           0.869719           0.862861           0.869310   

   mean_test_score  std_test_score  rank_test_score  
0         0.865391        0.002327                6  
1         0.867281        0.002696                3  
2         0.867222        0.002654                5  
3         0.867289        0.002711                2  
4         0.867315        0.002727                1  
5         0.867281        0.002696                3

In [28]:
analysis(Y_test, w2v_log.predict(X_test_w2v))

Report: Classification
               precision    recall  f1-score   support

    positive       0.88      0.85      0.86      5688
    negative       0.85      0.88      0.86      5562

    accuracy                           0.86     11250
   macro avg       0.86      0.86      0.86     11250
weighted avg       0.86      0.86      0.86     11250

Matrix: Confusion
 [[4821  867]
 [ 685 4877]]
Accuracy:
 0.8620444444444444


0.8627277551742437

### SVM

In [30]:
w2v_svm = svm.SVC()
w2v_svm = HalvingGridSearchCV(estimator=w2v_svm, param_grid=svc_grid, cv = 2, n_jobs= -1, scoring='f1', factor=2)
w2v_svm.fit(X_train_w2v, Y_train)
print(f'Best Score: {w2v_svm.best_score_}')
print(f'Best Params: {w2v_svm.best_params_}')
pd.DataFrame(w2v_svm.cv_results_)

Best Score: 0.8686236371763223
Best Params: {'C': 1, 'kernel': 'rbf'}


iter  n_resources  mean_fit_time  std_fit_time  mean_score_time  \
0      0         4218       3.940405      1.661494         1.103088   
1      0         4218       5.531537      0.362466         2.946180   
2      0         4218       5.316753      1.148359         0.587173   
3      0         4218       4.721053      0.477904         1.993583   
4      0         4218      72.122401      6.157075         0.252554   
5      0         4218       1.456833      0.251809         0.787516   
6      0         4218     154.232060      0.657518         0.295835   
7      0         4218       1.835010      0.763028         1.276727   
8      1         8436      46.107652      1.817349         9.450498   
9      1         8436      38.709924      0.934568        15.067066   
10     1         8436      35.454362      4.030234         6.015850   
11     1         8436      31.680514      3.484198        12.159924   
12     2        16872      69.224183      1.659582        33.955428   
13     2        16872      77.591265      1.190140        47.172871   
14     3        33744     146.867857      1.538679        86.052802   

    std_score_time param_C param_kernel                           params  \
0         0.008220     0.1       linear   {'C': 0.1, 'kernel': 'linear'}   
1         1.449964     0.1          rbf      {'C': 0.1, 'kernel': 'rbf'}   
2         0.041561       1       linear     {'C': 1, 'kernel': 'linear'}   
3         0.503912       1          rbf        {'C': 1, 'kernel': 'rbf'}   
4         0.008855     500       linear   {'C': 500, 'kernel': 'linear'}   
5         0.015626     500          rbf      {'C': 500, 'kernel': 'rbf'}   
6         0.004763    1000       linear  {'C': 1000, 'kernel': 'linear'}   
7         0.020805    1000          rbf     {'C': 1000, 'kernel': 'rbf'}   
8         1.612715     0.1          rbf      {'C': 0.1, 'kernel': 'rbf'}   
9         1.520572       1          rbf        {'C': 1, 'kernel': 'rbf'}   
10        2.291230       1       linear     {'C': 1, 'kernel': 'linear'}   
11        6.423774     0.1       linear   {'C': 0.1, 'kernel': 'linear'}   
12        8.883698     0.1       linear   {'C': 0.1, 'kernel': 'linear'}   
13        0.676267       1          rbf        {'C': 1, 'kernel': 'rbf'}   
14        1.130811       1          rbf        {'C': 1, 'kernel': 'rbf'}   

    split0_test_score  split1_test_score  mean_test_score  std_test_score  \
0            0.853249           0.861538         0.857393        0.004145   
1            0.841263           0.837341         0.839302        0.001961   
2            0.848235           0.864916         0.856576        0.008341   
3            0.851801           0.861244         0.856523        0.004721   
4            0.834888           0.842664         0.838776        0.003888   
5            0.812645           0.824266         0.818456        0.005810   
6            0.828545           0.843675         0.836110        0.007565   
7            0.812645           0.824266         0.818456        0.005810   
8            0.850897           0.845566         0.848232        0.002666   
9            0.865066           0.855869         0.860467        0.004599   
10           0.866230           0.852358         0.859294        0.006936   
11           0.865658           0.853383         0.859521        0.006137   
12           0.863143           0.862338         0.862741        0.000402   
13           0.864166           0.868179         0.866173        0.002007   
14           0.868312           0.868936         0.868624        0.000312   

    rank_test_score  split0_train_score  split1_train_score  mean_train_score  \
0                 7            0.881720            0.872483          0.877102   
1                11            0.860384            0.846081          0.853233   
2                 8            0.889689            0.884523          0.887106   
3                 9            0.907465            0.894712          0.901089   
4           

In [31]:
analysis(Y_test, w2v_svm.predict(X_test_w2v))

Report: Classification
               precision    recall  f1-score   support

    positive       0.88      0.85      0.87      5688
    negative       0.85      0.89      0.87      5562

    accuracy                           0.87     11250
   macro avg       0.87      0.87      0.87     11250
weighted avg       0.87      0.87      0.87     11250

Matrix: Confusion
 [[4819  869]
 [ 630 4932]]
Accuracy:
 0.8667555555555555


0.8680806125143008

### KNN

In [32]:
w2v_knn = KNeighborsClassifier()
w2v_knn = HalvingGridSearchCV(estimator=w2v_knn, param_grid=knn_grid, cv = 2, scoring='f1', factor=2)
w2v_knn.fit(X_train_w2v, Y_train)
print(f'Best Score: {w2v_knn.best_score_}')
print(f'Best Params: {w2v_knn.best_params_}')
pd.DataFrame(w2v_knn.cv_results_)

Best Score: 0.8046219952536993
Best Params: {'n_jobs': -1, 'n_neighbors': 100}


iter  n_resources  mean_fit_time  std_fit_time  mean_score_time  \
0      0         8437       0.037862      0.007212         2.239229   
1      0         8437       0.028378      0.000207         1.554471   
2      0         8437       0.031118      0.004500         1.649769   
3      0         8437       0.023090      0.000727         1.679940   
4      0         8437       0.029401      0.003737         1.902784   
5      0         8437       0.028024      0.004964         1.976717   
6      0         8437       0.027081      0.003388         2.824902   
7      1        16874       0.037361      0.000400        26.759446   
8      1        16874       0.033526      0.002737         5.729146   
9      1        16874       0.038860      0.007362         5.235834   
10     1        16874       0.036065      0.002759         4.755654   
11     2        33748       0.062026      0.004696        61.315143   
12     2        33748       0.059939      0.000419        18.684956   

    std_score_time param_n_jobs param_n_neighbors  \
0         0.627276           -1                 1   
1         0.012075           -1               100   
2         0.172171           -1               300   
3         0.121788           -1               500   
4         0.047222           -1               700   
5         0.133504           -1               900   
6         0.123307           -1              2000   
7        20.460729           -1               700   
8         0.210555           -1               500   
9         0.080959           -1               300   
10        0.071454           -1               100   
11       42.807390           -1               300   
12        0.488856           -1               100   

                                 params  split0_test_score  split1_test_score  \
0      {'n_jobs': -1, 'n_neighbors': 1}           0.724382           0.738973   
1    {'n_jobs': -1, 'n_neighbors': 100}           0.793792           0.781910   
2    {'n_jobs': -1, 'n_neighbors': 300}           0.774226           0.751298   
3    {'n_jobs': -1, 'n_neighbors': 500}           0.761119           0.732558   
4    {'n_jobs': -1, 'n_neighbors': 700}           0.750693           0.719035   
5    {'n_jobs': -1, 'n_neighbors': 900}           0.741886           0.707284   
6   {'n_jobs': -1, 'n_neighbors': 2000}           0.716846           0.670336   
7    {'n_jobs': -1, 'n_neighbors': 700}           0.746385           0.750697   
8    {'n_jobs': -1, 'n_neighbors': 500}           0.756903           0.759875   
9    {'n_jobs': -1, 'n_neighbors': 300}           0.766355           0.774337   
10   {'n_jobs': -1, 'n_neighbors': 100}           0.788459           0.788660   
11   {'n_jobs': -1, 'n_neighbors': 300}           0.796231           0.785060   
12   {'n_jobs': -1, 'n_neighbors': 100}           0.809071           0.800173   

    mean_test_score  std_test_score  rank_test_score  split0_train_score  \
0          0.731678        0.007295               11            1.000000   
1          0.787851        0.005941                4            0.795503   
2          0.762762        0.011464                6            0.770352   
3          0.746839        0.014281                9            0.759277   
4          0.734864        0.015829               10            0.747723   
5          0.724585        0.017301               12            0.741217   
6          0.693591        0.023255               13            0.712418   
7          0.748541        0.002156                8            0.754300   
8          0.758389        0.001486                7            0.761601   
9          0.770346        0.003991                5            0.776278   
10         0.788560        0.000101                3            0.798753   
11         0.790645        0.005586                2            0.795688   
12         0.804622        0.004449                1            0.812214   

    split1_train_score  mean_train_score  std_train_score  
0     

In [33]:
analysis(Y_test, w2v_svm.predict(X_test_w2v))

Report: Classification
               precision    recall  f1-score   support

    positive       0.88      0.85      0.87      5688
    negative       0.85      0.89      0.87      5562

    accuracy                           0.87     11250
   macro avg       0.87      0.87      0.87     11250
weighted avg       0.87      0.87      0.87     11250

Matrix: Confusion
 [[4819  869]
 [ 630 4932]]
Accuracy:
 0.8667555555555555


0.8680806125143008

## Comparison

In [34]:
summary = {
    'LR': {'BoW': bow_log, 'W2V': w2v_log},
    'SVM' : {'BoW': bow_svm, 'W2V': w2v_svm},
    'KNN': {'BoW': bow_knn, 'W2V': w2v_knn},
  }

for name, values in summary.items():
    print(f'For classifier {name}, best BoW score is {values["BoW"].best_score_}, whereas best W2V score is {values["W2V"].best_score_}')
    best_model = "BoW" if values["BoW"].best_score_ > values["W2V"].best_score_ else "W2V"
    print(f'So {best_model} is better with parameters {values[best_model].best_params_}')
    filename = name + '.pkl'
    with open(filename, 'wb') as f:
        pickle.dump(values[best_model], f)

del summary, bow_log, w2v_log, bow_svm, w2v_svm, bow_knn, w2v_knn

For classifier LR, best BoW score is 0.8657995144389071, whereas best W2V score is 0.8673145284043511
So W2V is better with parameters {'C': 900, 'class_weight': 'balanced', 'max_iter': 1000, 'n_jobs': -1, 'penalty': 'l2', 'solver': 'saga'}
For classifier SVM, best BoW score is 0.8677297881739967, whereas best W2V score is 0.8686236371763223
So W2V is better with parameters {'C': 1, 'kernel': 'rbf'}
For classifier KNN, best BoW score is 0.7344377977492681, whereas best W2V score is 0.8046219952536993
So W2V is better with parameters {'n_jobs': -1, 'n_neighbors': 100}


# MLP

In [35]:
mlp_grid = {
    'hidden_layer_sizes': [(500, 250), (1000, 250), (500, 250, 250), (1000, 500, 250), (500, 250, 250, 5),
                           (1000, 500, 250, 5)],
    'activation':['tanh', 'relu']
}
def eval_mlp(X_train, X_test, Y_train, Y_test):
    best_f1 = -1
    best_model = None
    for sizes in mlp_grid['hidden_layer_sizes']:
        for act in mlp_grid['activation']:
            m = MLPClassifier(hidden_layer_sizes=sizes, activation=act, solver='sgd', alpha=1,
                                    learning_rate='adaptive', max_iter=10)
            m.fit(X_train, Y_train)
            print(f'Model config: hidden_layer_sizes={sizes}, activation={act}')
            f1 = analysis(Y_test, m.predict(X_test))
            if f1 > best_f1:
                best_model = m
                best_f1 = f1
    return best_f1, best_model

## W2V

In [36]:
w2v_f1, w2v_mlp = eval_mlp(X_train_w2v, X_test_w2v, Y_train, Y_test)

/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


Model config: hidden_layer_sizes=(500, 250), activation=tanh
Report: Classification
               precision    recall  f1-score   support

    positive       0.87      0.83      0.85      5688
    negative       0.83      0.88      0.85      5562

    accuracy                           0.85     11250
   macro avg       0.85      0.85      0.85     11250
weighted avg       0.85      0.85      0.85     11250

Matrix: Confusion
 [[4714  974]
 [ 690 4872]]
Accuracy:
 0.8520888888888889


/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


Model config: hidden_layer_sizes=(500, 250), activation=relu
Report: Classification
               precision    recall  f1-score   support

    positive       0.87      0.83      0.85      5688
    negative       0.83      0.87      0.85      5562

    accuracy                           0.85     11250
   macro avg       0.85      0.85      0.85     11250
weighted avg       0.85      0.85      0.85     11250

Matrix: Confusion
 [[4731  957]
 [ 728 4834]]
Accuracy:
 0.8502222222222222


/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


Model config: hidden_layer_sizes=(1000, 250), activation=tanh
Report: Classification
               precision    recall  f1-score   support

    positive       0.87      0.83      0.85      5688
    negative       0.84      0.88      0.86      5562

    accuracy                           0.85     11250
   macro avg       0.85      0.85      0.85     11250
weighted avg       0.86      0.85      0.85     11250

Matrix: Confusion
 [[4742  946]
 [ 693 4869]]
Accuracy:
 0.8543111111111111


/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


Model config: hidden_layer_sizes=(1000, 250), activation=relu
Report: Classification
               precision    recall  f1-score   support

    positive       0.86      0.84      0.85      5688
    negative       0.84      0.86      0.85      5562

    accuracy                           0.85     11250
   macro avg       0.85      0.85      0.85     11250
weighted avg       0.85      0.85      0.85     11250

Matrix: Confusion
 [[4766  922]
 [ 769 4793]]
Accuracy:
 0.8496888888888889


/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


Model config: hidden_layer_sizes=(500, 250, 250), activation=tanh
Report: Classification
               precision    recall  f1-score   support

    positive       0.88      0.83      0.85      5688
    negative       0.84      0.88      0.86      5562

    accuracy                           0.86     11250
   macro avg       0.86      0.86      0.86     11250
weighted avg       0.86      0.86      0.86     11250

Matrix: Confusion
 [[4734  954]
 [ 669 4893]]
Accuracy:
 0.8557333333333333


/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


Model config: hidden_layer_sizes=(500, 250, 250), activation=relu
Report: Classification
               precision    recall  f1-score   support

    positive       0.88      0.82      0.85      5688
    negative       0.83      0.88      0.86      5562

    accuracy                           0.85     11250
   macro avg       0.85      0.85      0.85     11250
weighted avg       0.85      0.85      0.85     11250

Matrix: Confusion
 [[4673 1015]
 [ 643 4919]]
Accuracy:
 0.8526222222222222


/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


Model config: hidden_layer_sizes=(1000, 500, 250), activation=tanh
Report: Classification
               precision    recall  f1-score   support

    positive       0.87      0.85      0.86      5688
    negative       0.85      0.87      0.86      5562

    accuracy                           0.86     11250
   macro avg       0.86      0.86      0.86     11250
weighted avg       0.86      0.86      0.86     11250

Matrix: Confusion
 [[4813  875]
 [ 717 4845]]
Accuracy:
 0.8584888888888889


/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


Model config: hidden_layer_sizes=(1000, 500, 250), activation=relu
Report: Classification
               precision    recall  f1-score   support

    positive       0.87      0.83      0.85      5688
    negative       0.83      0.88      0.86      5562

    accuracy                           0.85     11250
   macro avg       0.85      0.85      0.85     11250
weighted avg       0.85      0.85      0.85     11250

Matrix: Confusion
 [[4722  966]
 [ 682 4880]]
Accuracy:
 0.8535111111111111


/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


Model config: hidden_layer_sizes=(500, 250, 250, 5), activation=tanh
Report: Classification
               precision    recall  f1-score   support

    positive       0.87      0.86      0.86      5688
    negative       0.85      0.86      0.86      5562

    accuracy                           0.86     11250
   macro avg       0.86      0.86      0.86     11250
weighted avg       0.86      0.86      0.86     11250

Matrix: Confusion
 [[4870  818]
 [ 755 4807]]
Accuracy:
 0.8601777777777778


/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


Model config: hidden_layer_sizes=(500, 250, 250, 5), activation=relu
Report: Classification
               precision    recall  f1-score   support

    positive       0.88      0.83      0.85      5688
    negative       0.83      0.88      0.86      5562

    accuracy                           0.85     11250
   macro avg       0.85      0.85      0.85     11250
weighted avg       0.85      0.85      0.85     11250

Matrix: Confusion
 [[4702  986]
 [ 660 4902]]
Accuracy:
 0.8536888888888889


/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


Model config: hidden_layer_sizes=(1000, 500, 250, 5), activation=tanh
Report: Classification
               precision    recall  f1-score   support

    positive       0.87      0.84      0.86      5688
    negative       0.84      0.87      0.86      5562

    accuracy                           0.86     11250
   macro avg       0.86      0.86      0.86     11250
weighted avg       0.86      0.86      0.86     11250

Matrix: Confusion
 [[4797  891]
 [ 710 4852]]
Accuracy:
 0.8576888888888888


/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


Model config: hidden_layer_sizes=(1000, 500, 250, 5), activation=relu
Report: Classification
               precision    recall  f1-score   support

    positive       0.87      0.84      0.86      5688
    negative       0.84      0.88      0.86      5562

    accuracy                           0.86     11250
   macro avg       0.86      0.86      0.86     11250
weighted avg       0.86      0.86      0.86     11250

Matrix: Confusion
 [[4776  912]
 [ 684 4878]]
Accuracy:
 0.8581333333333333


## BoW

In [ ]:
bow_f1, bow_mlp = eval_mlp(X_train_bow, X_test_bow, Y_train, Y_test)

/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


Model config: hidden_layer_sizes=(500, 250), activation=tanh
Report: Classification
               precision    recall  f1-score   support

    positive       0.88      0.84      0.86      5688
    negative       0.85      0.88      0.86      5562

    accuracy                           0.86     11250
   macro avg       0.86      0.86      0.86     11250
weighted avg       0.86      0.86      0.86     11250

Matrix: Confusion
 [[4795  893]
 [ 662 4900]]
Accuracy:
 0.8617777777777778


/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


Model config: hidden_layer_sizes=(500, 250), activation=relu
Report: Classification
               precision    recall  f1-score   support

    positive       0.86      0.83      0.85      5688
    negative       0.83      0.87      0.85      5562

    accuracy                           0.85     11250
   macro avg       0.85      0.85      0.85     11250
weighted avg       0.85      0.85      0.85     11250

Matrix: Confusion
 [[4717  971]
 [ 748 4814]]
Accuracy:
 0.8472


/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


Model config: hidden_layer_sizes=(1000, 250), activation=tanh
Report: Classification
               precision    recall  f1-score   support

    positive       0.87      0.85      0.86      5688
    negative       0.85      0.87      0.86      5562

    accuracy                           0.86     11250
   macro avg       0.86      0.86      0.86     11250
weighted avg       0.86      0.86      0.86     11250

Matrix: Confusion
 [[4832  856]
 [ 697 4865]]
Accuracy:
 0.8619555555555556


/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


Model config: hidden_layer_sizes=(1000, 250), activation=relu
Report: Classification
               precision    recall  f1-score   support

    positive       0.88      0.82      0.85      5688
    negative       0.83      0.88      0.86      5562

    accuracy                           0.85     11250
   macro avg       0.86      0.85      0.85     11250
weighted avg       0.86      0.85      0.85     11250

Matrix: Confusion
 [[4691  997]
 [ 646 4916]]
Accuracy:
 0.8539555555555556


/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


Model config: hidden_layer_sizes=(500, 250, 250), activation=tanh
Report: Classification
               precision    recall  f1-score   support

    positive       0.87      0.86      0.86      5688
    negative       0.85      0.87      0.86      5562

    accuracy                           0.86     11250
   macro avg       0.86      0.86      0.86     11250
weighted avg       0.86      0.86      0.86     11250

Matrix: Confusion
 [[4865  823]
 [ 721 4841]]
Accuracy:
 0.8627555555555556


/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


Model config: hidden_layer_sizes=(500, 250, 250), activation=relu
Report: Classification
               precision    recall  f1-score   support

    positive       0.87      0.83      0.85      5688
    negative       0.84      0.87      0.85      5562

    accuracy                           0.85     11250
   macro avg       0.85      0.85      0.85     11250
weighted avg       0.85      0.85      0.85     11250

Matrix: Confusion
 [[4748  940]
 [ 732 4830]]
Accuracy:
 0.8513777777777778


/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


Model config: hidden_layer_sizes=(1000, 500, 250), activation=tanh
Report: Classification
               precision    recall  f1-score   support

    positive       0.88      0.85      0.86      5688
    negative       0.85      0.88      0.87      5562

    accuracy                           0.87     11250
   macro avg       0.87      0.87      0.87     11250
weighted avg       0.87      0.87      0.87     11250

Matrix: Confusion
 [[4826  862]
 [ 651 4911]]
Accuracy:
 0.8655111111111111


/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


Model config: hidden_layer_sizes=(1000, 500, 250), activation=relu
Report: Classification
               precision    recall  f1-score   support

    positive       0.87      0.85      0.86      5688
    negative       0.85      0.87      0.86      5562

    accuracy                           0.86     11250
   macro avg       0.86      0.86      0.86     11250
weighted avg       0.86      0.86      0.86     11250

Matrix: Confusion
 [[4811  877]
 [ 729 4833]]
Accuracy:
 0.8572444444444445


/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


Model config: hidden_layer_sizes=(500, 250, 250, 5), activation=tanh
Report: Classification
               precision    recall  f1-score   support

    positive       0.88      0.86      0.87      5688
    negative       0.86      0.88      0.87      5562

    accuracy                           0.87     11250
   macro avg       0.87      0.87      0.87     11250
weighted avg       0.87      0.87      0.87     11250

Matrix: Confusion
 [[4877  811]
 [ 694 4868]]
Accuracy:
 0.8662222222222222


/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


Model config: hidden_layer_sizes=(500, 250, 250, 5), activation=relu
Report: Classification
               precision    recall  f1-score   support

    positive       0.87      0.85      0.86      5688
    negative       0.85      0.87      0.86      5562

    accuracy                           0.86     11250
   macro avg       0.86      0.86      0.86     11250
weighted avg       0.86      0.86      0.86     11250

Matrix: Confusion
 [[4823  865]
 [ 747 4815]]
Accuracy:
 0.8567111111111111


/home/jupyter/ml_final_project/venv/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


Model config: hidden_layer_sizes=(1000, 500, 250, 5), activation=tanh
Report: Classification
               precision    recall  f1-score   support

    positive       0.87      0.87      0.87      5688
    negative       0.86      0.87      0.87      5562

    accuracy                           0.87     11250
   macro avg       0.87      0.87      0.87     11250
weighted avg       0.87      0.87      0.87     11250

Matrix: Confusion
 [[4929  759]
 [ 706 4856]]
Accuracy:
 0.8697777777777778


## TD-IDF

In [ ]:
vectorizer = TfidfVectorizer(max_features=2000)
X_train_idf = vectorizer.fit_transform(X_train)
X_test_idf = vectorizer.transform(X_test)

In [ ]:
tf_idf_f1, tf_idf_mlp = eval_mlp(X_train_idf, X_test_idf, Y_train, Y_test)

## Comparison

In [ ]:
print('Best scores:')
print(f'W2V: {w2v_f1} with params: {w2v_mlp.get_params()}')
print(f'BoW: {bow_f1} with params: {bow_mlp.get_params()}')
print(f'Tf-Idf: {tf_idf_f1} with params: {tf_idf_mlp.get_params()}')

idx = np.argmax([w2v_f1, bow_f1, tf_idf_f1])
best_mlp = [w2v_mlp, bow_mlp, tf_idf_mlp][idx]
with open('best.pkl', 'wb') as f:
    pickle.dump(best_mlp, f)
